image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      sudo apt-get update
      sudo apt-get install -y xfce4 xfce4-goodies xrdp
      sudo service xrdp start

ports:
  - port: 3389
    onOpen: ignore  # Change `ignore` to `open-preview` or another action if you want to automatically open the port.

vscode:
  extensions:
    - ms-vscode-remote.remote-wsl
